### ISSUE TITLE
Base64 mismatch

### ISSUE THREAD

**Issue by danielmohacsi** [angelim/snowly#1]
Hey, first of all - thank you for this awesome tool!

I have an existing project set up with the mini pipeline, and a lot of custom contexts and events, but it's cumbersome to upload the schema each time I change it, so I decided to use this tool for my next schema update.

I was getting the following error on each of my `page_view` events (I've got a few custom contexts on the `page_view` event):

`All custom contexts must be contain a `data` element`

I started playing around with the code, and it seems that the base64 decoding method you use does not accept values encoded by the Snowplow JavaScript tracker. If I change the `Base64.urlsafe_decode64` call in transformer.rb to `Base64.decode64`, the tool accepts my events.

What's the reason you chose the `urlsafe_decode64` instead of the `decode64` method?

**Comment by angelim** [comment]
Hi @danielmohacsi. You're most welcome and thank you for taking the time to dig this up.
I thought `#urlsafe_decode64` was required when I found some code in the enrichment process that used safe url decoding: [ConvertionUtils.scala](https://github.com/snowplow/snowplow/blob/b772f6e089bb9e0b3bdbed93a4ab18902c4f1a4a/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/ConversionUtils.scala#L152) and how it was being used when extracting information from an encoded context, [here](https://github.com/snowplow/snowplow/blob/b772f6e089bb9e0b3bdbed93a4ab18902c4f1a4a/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/snowplow/RedirectAdapter.scala#L190).

Now that you brought this up, I took a look at the ruby-tracker and realized it was encoding contexts with strict_encode64 and not with urlsafe_encode64, just like the javascript tracker.

It's fixed on master now and 0.1.5 was pushed to rubygems.org

**Comment by danielmohacsi** [comment]
Wow, thanks for the quick response! I will check the fix soon.

**Comment by danielmohacsi** [comment]
I did a lookup to the JS tracker's [code](https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/core/lib/payload.js#L35) and it seems to me that it is using the urlsafe base64 encoding, but they remove the padding from the encoded string.
At the same time, it seems that the Ruby base64 module's `strict_decode64` and `urlsafe_decode64` methods throw an error if the padding is incorrect.
It's fine, because I can turn off the base64 encoding in my web project, and use snowly.

**Comment by angelim** [comment]
Let's just leave it the way you found it to work, using `Base64.decode64` plain and simply. I don't think loosening these rules will get us in trouble because users won't be responsible for encoding contexts anyway. If `Base64.decode64` works for the current trackers, I'm fine with it.

**Comment by danielmohacsi** [comment]
It works for well the JS tracker, I don't know about the other trackers.

**Comment by angelim** [comment]
Worked with the ruby tracker as well. Lets see if someone else, using other
tracker, complains down the road. For now I think we should stick with your
solution.

Em quarta-feira, 15 de junho de 2016, Daniel Mohacsi <
notifications@github.com> escreveu:

**Comment by danielmohacsi** [comment]
Great, thanks! I can ask a team-mate to test snowly with the Java collector if that helps.

**Comment by angelim** [comment]
That would be great. Thanks

Em quarta-feira, 15 de junho de 2016, Daniel Mohacsi <
notifications@github.com> escreveu:

**Comment by danielmohacsi** [comment]
We have tested snowly with the Java tracker with base64 encoding and with [POST support](https://github.com/angelim/snowly/pull/3).
Everything worked fine!
